CREATE TABLE [dbo].[Users]
(
	[UserId] INT CONSTRAINT PK_Users_UserId PRIMARY KEY IDENTITY(1,1) NOT NULL,
	[Email] NVARCHAR(50),
	[Password] NVARCHAR(50),
	[FName] NVARCHAR(30),
	[LName] NVARCHAR(30),
	[RegistrationDate] DATETIME NOT NULL,
	[State] TINYINT NOT NULL DEFAULT 0,
	[Role] TINYINT NOT NULL,
	[Delisted] BIT NOT NULL DEFAULT 0
)
